baseurl      = "https://fearian.github.io/"
title        = "Fearian"
languageCode = "en-uk"
theme        = "hello-friend-ng"
paginate     = 10
publishDir   = "docs"
features = ["social icons"]

[params]
  defaultTheme = "dark"
  EnableThemeToggle = "true"

  dateform        = "2 Jan, 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"


  # Subtitle for home
  homeSubtitle = "Here's where you can find me on the world wide web"


  [[params.social]]
    name = "artstation"
    title = "Portfolio"
    url = "http://fearian.com/"
  [[params.social]]
    name = "bluesky"
    title = "Bluesky"
    url = "https://fearian.bsky.social"
  [[params.social]]
    name = "twitter"
    title = "Twitter"
    url = "https://twitter.com/fearian"
  [[params.social]]
    name = "github"
    title = "GitHub"
    url = "https://github.com/fearian"
  [[params.social]]
    name = "itch.io"
    title = "itch.io"
    url = "https://fearian.itch.io"
  [[params.social]]
    name = "youtube"
    title = "YouTube"
    url = "https://youtube.com/fearian"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "Links to my spaces on the web"
  keywords = "links, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "@fearian"
    subtitle = "Here's where you can find me on the world wide web"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Ian Maclure"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"